baseURL = 'https://seancc.github.io/'
languageCode = 'en-us'
title = 'Charlie Carter'
theme = 'hugo-ink'

[params]
	subtitle = "Portfolio & Blog"

	# Optional 64x64 avatar image.
	avatar = "https://i.imgur.com/eheqmQ8.jpg"

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]
	
	featherIconsCDN = true

	mode = "auto" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts

[taxonomies]
  tag = "tags"
  category = "categories"

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3